language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
    - nvm install 6

install:
  - python3 setup.py deps_install

script:
  - python3 setup.py lint
  - python3 setup.py test
  - python3 setup.py e2e_test
