sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install npm@latest -g

install:
  - python setup.py deps_install

script:
  - python setup.py lint
  - python setup.py test
  - python setup.py e2e_test
